
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Braille", targetNamespace = "http://www.webserviceX.NET", wsdlLocation = "http://www.webservicex.net/braille.asmx?WSDL")
public class Braille
    extends Service
{

    private final static URL BRAILLE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.webservicex.Braille.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.webservicex.Braille.class.getResource(".");
            url = new URL(baseUrl, "http://www.webservicex.net/braille.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.webservicex.net/braille.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BRAILLE_WSDL_LOCATION = url;
    }

    public Braille(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Braille() {
        super(BRAILLE_WSDL_LOCATION, new QName("http://www.webserviceX.NET", "Braille"));
    }

    /**
     * 
     * @return
     *     returns BrailleSoap
     */
    @WebEndpoint(name = "BrailleSoap")
    public BrailleSoap getBrailleSoap() {
        return super.getPort(new QName("http://www.webserviceX.NET", "BrailleSoap"), BrailleSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BrailleSoap
     */
    @WebEndpoint(name = "BrailleSoap")
    public BrailleSoap getBrailleSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webserviceX.NET", "BrailleSoap"), BrailleSoap.class, features);
    }

}
