
package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TranslateService", targetNamespace = "http://www.webservicex.net", wsdlLocation = "http://www.webservicex.net/TranslateService.asmx?WSDL")
public class TranslateService
    extends Service
{

    private final static URL TRANSLATESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.webservicex.TranslateService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.webservicex.TranslateService.class.getResource(".");
            url = new URL(baseUrl, "http://www.webservicex.net/TranslateService.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.webservicex.net/TranslateService.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TRANSLATESERVICE_WSDL_LOCATION = url;
    }

    public TranslateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TranslateService() {
        super(TRANSLATESERVICE_WSDL_LOCATION, new QName("http://www.webservicex.net", "TranslateService"));
    }

    /**
     * 
     * @return
     *     returns TranslateServiceSoap
     */
    @WebEndpoint(name = "TranslateServiceSoap")
    public TranslateServiceSoap getTranslateServiceSoap() {
        return super.getPort(new QName("http://www.webservicex.net", "TranslateServiceSoap"), TranslateServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TranslateServiceSoap
     */
    @WebEndpoint(name = "TranslateServiceSoap")
    public TranslateServiceSoap getTranslateServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webservicex.net", "TranslateServiceSoap"), TranslateServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns TranslateServiceSoap
     */
    @WebEndpoint(name = "TranslateServiceSoap12")
    public TranslateServiceSoap getTranslateServiceSoap12() {
        return super.getPort(new QName("http://www.webservicex.net", "TranslateServiceSoap12"), TranslateServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TranslateServiceSoap
     */
    @WebEndpoint(name = "TranslateServiceSoap12")
    public TranslateServiceSoap getTranslateServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webservicex.net", "TranslateServiceSoap12"), TranslateServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns TranslateServiceHttpGet
     */
    @WebEndpoint(name = "TranslateServiceHttpGet")
    public TranslateServiceHttpGet getTranslateServiceHttpGet() {
        return super.getPort(new QName("http://www.webservicex.net", "TranslateServiceHttpGet"), TranslateServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TranslateServiceHttpGet
     */
    @WebEndpoint(name = "TranslateServiceHttpGet")
    public TranslateServiceHttpGet getTranslateServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webservicex.net", "TranslateServiceHttpGet"), TranslateServiceHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns TranslateServiceHttpPost
     */
    @WebEndpoint(name = "TranslateServiceHttpPost")
    public TranslateServiceHttpPost getTranslateServiceHttpPost() {
        return super.getPort(new QName("http://www.webservicex.net", "TranslateServiceHttpPost"), TranslateServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TranslateServiceHttpPost
     */
    @WebEndpoint(name = "TranslateServiceHttpPost")
    public TranslateServiceHttpPost getTranslateServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webservicex.net", "TranslateServiceHttpPost"), TranslateServiceHttpPost.class, features);
    }

}
