
package hello;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CalculatriceFunctionsService", targetNamespace = "http://hello/", wsdlLocation = "http://localhost:8080/WebServiceExample/calculatricefunctions/moins?wsdl")
public class CalculatriceFunctionsService
    extends Service
{

    private final static URL CALCULATRICEFUNCTIONSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(hello.CalculatriceFunctionsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = hello.CalculatriceFunctionsService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/WebServiceExample/calculatricefunctions/moins?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/WebServiceExample/calculatricefunctions/moins?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CALCULATRICEFUNCTIONSSERVICE_WSDL_LOCATION = url;
    }

    public CalculatriceFunctionsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatriceFunctionsService() {
        super(CALCULATRICEFUNCTIONSSERVICE_WSDL_LOCATION, new QName("http://hello/", "CalculatriceFunctionsService"));
    }

    /**
     * 
     * @return
     *     returns CalculatriceFunctions
     */
    @WebEndpoint(name = "CalculatriceFunctionsPort")
    public CalculatriceFunctions getCalculatriceFunctionsPort() {
        return super.getPort(new QName("http://hello/", "CalculatriceFunctionsPort"), CalculatriceFunctions.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatriceFunctions
     */
    @WebEndpoint(name = "CalculatriceFunctionsPort")
    public CalculatriceFunctions getCalculatriceFunctionsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello/", "CalculatriceFunctionsPort"), CalculatriceFunctions.class, features);
    }

}
