
package hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CalculatriceFunctions", targetNamespace = "http://hello/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatriceFunctions {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "plus", targetNamespace = "http://hello/", className = "hello.Plus")
    @ResponseWrapper(localName = "plusResponse", targetNamespace = "http://hello/", className = "hello.PlusResponse")
    public double plus(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "moins", targetNamespace = "http://hello/", className = "hello.Moins")
    @ResponseWrapper(localName = "moinsResponse", targetNamespace = "http://hello/", className = "hello.MoinsResponse")
    public double moins(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fois", targetNamespace = "http://hello/", className = "hello.Fois")
    @ResponseWrapper(localName = "foisResponse", targetNamespace = "http://hello/", className = "hello.FoisResponse")
    public double fois(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://hello/", className = "hello.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://hello/", className = "hello.DivisionResponse")
    public double division(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
