
package hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CircleFunctions", targetNamespace = "http://hello/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CircleFunctions {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArea", targetNamespace = "http://hello/", className = "hello.GetArea")
    @ResponseWrapper(localName = "getAreaResponse", targetNamespace = "http://hello/", className = "hello.GetAreaResponse")
    public double getArea(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCircumference", targetNamespace = "http://hello/", className = "hello.GetCircumference")
    @ResponseWrapper(localName = "getCircumferenceResponse", targetNamespace = "http://hello/", className = "hello.GetCircumferenceResponse")
    public double getCircumference(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
